version: '3.8'

services:
  redis:
    image: redis
    ports:
      - "6379:6379"
    restart: always

  sender:
    build:
      dockerfile: sender.Dockerfile
    restart: always
    volumes:
      - .:/app
    depends_on:
      - redis
