version: '3.8'

services:
  redis:
    image: redis
    ports:
      - "6379:6379"
    restart: always

  publisher:
    build:
      dockerfile: publisher.Dockerfile
    restart: always
    volumes:
      - .:/app
    depends_on:
      - redis

  consumer:
    build:
      dockerfile: consumer.Dockerfile
    restart: always
    volumes:
      - .:/app
    depends_on:
      - redis

  db:
    image: mysql:8
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root123
      MYSQL_DATABASE: notify
      MYSQL_USER: user
      MYSQL_PASSWORD: user123
    volumes:
      - mysql_db:/var/lib/mysql/

volumes:
  mysql_db:
